version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "ON"
    working_directory: ~/hello-gin
    steps:
      - checkout
      - run: go test ./...